<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Pump Socket</title>
    <meta charset="utf-8">
    <style>
      body {
        margin: 0px;
        background-color: #999999;
        overflow: hidden;
      }

      #buttons {
        position: absolute;
        top:5px;
        left:5px;
      }
    </style>
    <script src="FileSaver.js"></script>
    <script src="three.min.js"></script>
    <script src="csg.js"></script>
    <script src="orbit_controls.js"></script>
    <script src="ThreeCSG.js"></script>
    <script src="cad.js"></script>
    <script src="manifold.js"></script>
  </head>
  <body>
    <div id="buttons"></div>
    <script>

var M = manifold;

var PREPARE_FOR_PRINTING = true;
var CYLINDER_QUALITY = 128;

var WIDTH = 19.5;
var HEIGHT = 10.5;
var DEPTH = 7.5;
var LEFT_CORNER = 3.15;
var NOTCH_CENTER = 9.5;
var NOTCH_HEIGHT = 1.75;
var RIGHT_CORNER_RADIUS = 7.0;
var RIGHT_CORNER_CONTROL = 5;
var HOLE_HEIGHT = 5.25;
var LEFT_HOLE_X = 5.25;
var RIGHT_HOLE_X = 14.25;
var HOLE_RADIUS = 1.8;

var SIDE_MARGIN = 2.6;
var TOP_MARGIN = 1;
var OUTER_DEPTH = 2;

a3d.cad.init();
addGeometry();
a3d.cad.render();

function addGeometry() {
  if (PREPARE_FOR_PRINTING) {
    var csgRenderer = M.CSGRenderer();
    var renderer = csgRenderer.renderer;
  } else {
    var threeGeometry = M.ThreeJSRenderer();
    var geometry = threeGeometry.geometry;
    var renderer = threeGeometry.renderer;
  }

  var spine = M.Path([1,0,-OUTER_DEPTH])
    .line([1,0,0])
    .line([0,0,0])
    .line([0,0,DEPTH]);

  M.lift(spine.vertices(4,0))
    .generate(
      M.Sequencer([
        [2, M.VertexParameterizedPath(outerPath, 4)],
        [2, M.VertexParameterizedPath(innerPath, 50)]
      ]),
      M.facers( M.closeEdge, M.skin, M.capTop, M.capBottom )
    )
    .render(renderer);


  if (PREPARE_FOR_PRINTING) {
    var geometry = THREE.CSG.fromCSG(
      csgRenderer.csgObject()
        .subtract(CSG.cylinder({
          start: [LEFT_HOLE_X, HOLE_HEIGHT, 0],
          end: [LEFT_HOLE_X, HOLE_HEIGHT, DEPTH+1],
          radius: HOLE_RADIUS,
          slices: 40
        }))
        .subtract(CSG.cylinder({
          start: [RIGHT_HOLE_X, HOLE_HEIGHT, 0],
          end: [RIGHT_HOLE_X, HOLE_HEIGHT, DEPTH+1],
          radius: HOLE_RADIUS,
          slices: 40
        }))
        .subtract(CSG.cube({
          center: [LEFT_HOLE_X, HOLE_HEIGHT-3*HOLE_RADIUS/4, -OUTER_DEPTH/2],
          radius: [HOLE_RADIUS, HOLE_RADIUS/4, 1.2*OUTER_DEPTH/2]
        }))
        .subtract(CSG.cube({
          center: [RIGHT_HOLE_X, HOLE_HEIGHT-3*HOLE_RADIUS/4  , -OUTER_DEPTH/2],
          radius: [HOLE_RADIUS, HOLE_RADIUS/4, 1.2*OUTER_DEPTH/2]
        }))
    );
  } else {
    geometry.computeBoundingSphere();
    geometry.computeFaceNormals();
  }

  addMesh(geometry, '#ffffff', 'socket');
}

function innerPath(vertex) {
  return M.Path([0,0,vertex.z])
    .line([0, HEIGHT - RIGHT_CORNER_RADIUS, vertex.z])
    .curve([[0, HEIGHT - RIGHT_CORNER_RADIUS + RIGHT_CORNER_CONTROL, vertex.z],
            [RIGHT_CORNER_RADIUS - RIGHT_CORNER_CONTROL, HEIGHT, vertex.z],
            [RIGHT_CORNER_RADIUS,HEIGHT,vertex.z]], 10)
    .line([WIDTH-NOTCH_CENTER-NOTCH_HEIGHT, HEIGHT, vertex.z])
    .line([WIDTH-NOTCH_CENTER, HEIGHT-NOTCH_HEIGHT, vertex.z])
    .line([WIDTH-NOTCH_CENTER+NOTCH_HEIGHT, HEIGHT, vertex.z])
    .line([WIDTH-LEFT_CORNER,HEIGHT,vertex.z])
    .line([WIDTH,HEIGHT-LEFT_CORNER,vertex.z])
    .line([WIDTH,LEFT_CORNER,vertex.z])
    .line([WIDTH-LEFT_CORNER,0,vertex.z])
}

function outerPath(vertex) {
  return M.Path([-SIDE_MARGIN, -TOP_MARGIN, vertex.z])
    .line([-SIDE_MARGIN, HEIGHT + TOP_MARGIN, vertex.z])
    .line([WIDTH+SIDE_MARGIN, HEIGHT + TOP_MARGIN, vertex.z])
    .line([WIDTH+SIDE_MARGIN, -TOP_MARGIN, vertex.z])
}

function lerp(a, b, x) {
  return a + x*(b-a);
}

function rotateXY(p, angle) {
  var sa = Math.sin(angle), ca = Math.cos(angle);
  return [p[0]*ca + p[1]*sa, p[1]*ca - p[0]*sa, p[2] ];
}

function CircleTransformer(vertexSink) {
  var segments = [6,6,6,6,6,12,24,48,80];
  return function( vertex ) {
    M.CircleRib( segments[0], [0,0,1] )(vertexSink)(vertex);
    if (segments.length>1) segments = segments.slice(1);
  }
}

function fanCouplingPath(profile) {
  var r = FAN_COUPLING_RADIUS, cr = FAN_COUPLING_CORNER_RADIUS;
  return M.Path([r, cr-r, profile.z])
    .curve([[r, -r, profile.z], [r-cr, -r, profile.z]])
    .line([cr-r, -r, profile.z])
    .curve([[-r, -r, profile.z], [-r, cr-r, profile.z]])
    .line([-r, r-cr, profile.z])
    .curve([[-r, r, profile.z], [cr-r, r, profile.z]])
    .line([r-cr, r, profile.z])
    .curve([[r, r, profile.z], [r, r-cr, profile.z]])
}

function fanCouplingTopPath(profile) {
  var r = FAN_COUPLING_RADIUS, cr = FAN_COUPLING_CUTOUT;
  return M.Path([r, cr-r, profile.z])
    .line([r-cr, -r, profile.z])
    .line([cr-r, -r, profile.z])
    .line([-r, cr-r, profile.z])
    .line([-r, r-cr, profile.z])
    .line([cr-r, r, profile.z])
    .line([r-cr, r, profile.z])
    .line([r, r-cr, profile.z])
}

function addMesh( geometry, color, name ) {
  var material = new THREE.MeshPhongMaterial( { color: color } );
  var mesh = new THREE.Mesh(geometry, material );
  a3d.cad.addMesh(mesh, name)
}


    </script>
  </body>
</html>

