<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Servo 3</title>
    <meta charset="utf-8">
    <style>
      body {
        margin: 0px;
        background-color: #999999;
        overflow: hidden;
      }

      #buttons {
        position: absolute;
        top:5px;
        left:5px;
      }
    </style>
    <script src="FileSaver.js"></script>
    <script src="three.min.js"></script>
    <script src="csg.js"></script>
    <script src="orbit_controls.js"></script>
    <script src="ThreeCSG.js"></script>
    <script src="cad.js"></script>
    <script src="manifold.js"/></script>
  </head>
  <body>
    <div id="buttons"></div>
    <script>

var PREPARE_FOR_PRINTING = true;
var CYLINDER_QUALITY = PREPARE_FOR_PRINTING ? 50 : 20;

var PART_TOLERANCE = .1;

var TUBE_OUTER = 14;
var TUBE_DIAMETER = 10;
var TUBE_LENGTH = 28;
var TUBE_CUT = .5 * TUBE_DIAMETER;
var PIVOT_DIAMETER = 5.5;
var CONN_HOLE_SEP = 23.5;
var CONN_HOLE_OUTER = 5;
var CONN_HOLE_DIAMETER = 1.6;
var CONN_OUTER = CONN_HOLE_SEP + CONN_HOLE_OUTER;
var BASE_WIDTH = 9.5;

a3d.cad.init();
addGeometry();
a3d.cad.render();

function addGeometry() {


  var holderObj = CSG.cube({
    center: [0, (BASE_WIDTH + TUBE_DIAMETER)/2, TUBE_LENGTH/2],
    radius: [TUBE_OUTER/2, TUBE_OUTER/2, TUBE_LENGTH/2]
  }).subtract(CSG.cylinder({
    start:[0, (BASE_WIDTH + TUBE_DIAMETER)/2, 0],
    end:[0, (BASE_WIDTH + TUBE_DIAMETER)/2, TUBE_LENGTH],
    radius: TUBE_DIAMETER/2,
    slices: CYLINDER_QUALITY
  })).subtract(CSG.cube({
    center: [0, BASE_WIDTH/2 + TUBE_DIAMETER, TUBE_LENGTH/2],
    radius: [TUBE_OUTER, TUBE_CUT, TUBE_LENGTH]
  })).subtract(CSG.cylinder({
    start: [-TUBE_OUTER, (BASE_WIDTH + TUBE_DIAMETER)/2, TUBE_LENGTH/2],
    end: [TUBE_OUTER, (BASE_WIDTH + TUBE_DIAMETER)/2, TUBE_LENGTH/2],
    radius: PIVOT_DIAMETER/2,
    slices: CYLINDER_QUALITY
  })).subtract(CSG.cube({
    center: [0, (BASE_WIDTH + TUBE_DIAMETER + PIVOT_DIAMETER)/2, TUBE_LENGTH/2],
    radius: [TUBE_OUTER, PIVOT_DIAMETER/2, PIVOT_DIAMETER/2]
  }))



  holderObj = holderObj.union(CSG.cube({
    center: [0, 0, CONN_OUTER/2],
    radius: [CONN_OUTER/2, BASE_WIDTH/2, CONN_OUTER/2]
  }))

  for (var i=-1;i<2;i+=2) for (var j=-1;j<2;j+=2)
    holderObj = holderObj.subtract(CSG.cylinder({
      start:[i*CONN_HOLE_SEP/2,  -2*BASE_WIDTH, CONN_HOLE_OUTER/2 + (.5+j/2)*CONN_HOLE_SEP],
      end:[i*CONN_HOLE_SEP/2,  2*BASE_WIDTH, CONN_HOLE_OUTER/2 + (.5+j/2)*CONN_HOLE_SEP],
      radius: CONN_HOLE_DIAMETER/2,
      slices: CYLINDER_QUALITY
    }))

  holderObj = holderObj.subtract(CSG.cylinder({
    start:[0, -8, -1],
    end:[0, -8, CONN_OUTER + 1],
    radius: 10,
    slices: CYLINDER_QUALITY
  }))

  holderObj = holderObj.subtract(CSG.cylinder({
    start:[-CONN_OUTER, -8, CONN_OUTER/2],
    end:[CONN_OUTER, -8, CONN_OUTER/2],
    radius: 10,
    slices: CYLINDER_QUALITY
  }))


  var geometry = THREE.CSG.fromCSG(holderObj);
  // THREE.GeometryUtils.merge(trapGeometry, dishGeometry)
  addMesh( geometry, '#ffffff', 'connector3');
}

function addMesh( geometry, color, name ) {
  var material = new THREE.MeshPhongMaterial( { color: color } );
  var mesh = new THREE.Mesh(geometry, material );
  a3d.cad.addMesh(mesh, name, {edge: .1})
}

function translateGeometry( g, x, y, z ) {
  matrix = new THREE.Matrix4().makeTranslation(x,y,z);
  g.applyMatrix(matrix);
}
function rotateGeometry( g, x, y, z ) {
  var matrix;
  if (x)
    matrix = new THREE.Matrix4().makeRotationX(x);
  if (y)
    matrix = (matrix||new THREE.Matrix4()).makeRotationY(y);
  if (z)
    matrix = (matrix||new THREE.Matrix4()).makeRotationZ(z);
  if (matrix)
    g.applyMatrix(matrix);
}
function scaleGeometry( g, x, y, z ) {
  matrix = new THREE.Matrix4().makeScale(x,y,z);
  g.applyMatrix(matrix);
}

    </script>
  </body>
</html>